language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls

services:
  - postgresql

before_script:
- psql -c "CREATE DATABASE test_andela;" 
- psql -c "CREATE USER postgres WITH PASSWORD 'leah';" -U postgres

script: 
  - cd api/v2/
  - ls -la
  - python -m pytest --cov-report term-missing --cov=app

after_success:
  - coveralls

cache: pip
