language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:

  - psql -c 'create database test_andela;' -U postgres

script: 
  - cd api/v2/
  - ls -la
  - pytest --cov-report term-missing --cov=app

after_success:
  - coveralls

cache: pip
