language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls

script: 
  - cd api/v1/
  - pytest --cov-report term-missing --cov=app

after_success:
  - coveralls

cache: pip
